apply plugin: 'com.android.application'

android {
    compileSdkVersion 33
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.liudonghan.base"
        minSdkVersion 24
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    signingConfigs {
        release {
            storeFile file("../liu.keystore")
            storePassword "123456"
            keyAlias "key"
            keyPassword "123456"
        }
    }

    buildTypes {
        release {
            zipAlignEnabled true
            signingConfig signingConfigs.release  //使用上述签名信息
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "boolean", "isProduction", "false"
        }
        debug {
            minifyEnabled false
            //debug时使用release签名
            signingConfig signingConfigs.release
            //Zip代码压缩优化
            zipAlignEnabled true
            buildConfigField "boolean", "isProduction", "false"
        }
        predebug.initWith(debug)
        predebug {
            signingConfig signingConfigs.release
            buildConfigField "boolean", "isProduction", "true"
        }
    }

    buildFeatures{
        viewBinding = true
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation project(':mvp')
    // google
    implementation 'com.google.code.gson:gson:2.10'

    implementation 'com.github.18647499996:Component:3.1.2'
    implementation 'com.github.18647499996:Utils:2.5.6'
    implementation 'com.github.18647499996:multi-image-selector:2.0.2'
}
